### ISSUE TITLE
[BUG] "Cancel", "Back" and "Next" Buttons Not Working for Equipment Used Page when Adding Procedure 

### ISSUE THREAD

**Issue by eyl1532** [Carebase-Solutions/carebase-android#40]
### Description
When adding procedure, on the "Equipment used" page, if we don't add any equipment and click on "Cancel" or "Next", nothing happens and no message displayed

![image](https://user-images.githubusercontent.com/35200947/94739745-707d1280-033f-11eb-9b27-1a5d514f9a61.png)

If we click on the "Back" arrow on the top left, we jump to the inventory screen first, then Procedure Information screen. Although the accession number is filled in, we cannot advance without clicking on the accession number again and generating a new one. 

### Solution
Redo UX for "Back," "Cancel," and "Next"?

(Also capitalize first letter of each word for page headers and section headers?)

**Comment by sak6lab** [comment]
I would get rid of the menu buttons and fix the back button.
