### ISSUE TITLE
Add labels to mini floating action buttons

### ISSUE THREAD

**Issue by sak6lab** [Carebase-Solutions/carebase-android#74]
### How it is now
In the branch, ui_redesign, the mini floating action buttons that appear after the main floating action button is pressed does not have labels.

<img width="72" alt="Screen Shot 2021-02-01 at 9 45 53 AM" src="https://user-images.githubusercontent.com/15002610/106474662-25047d80-6473-11eb-8874-fc456684dcff.png">

### What to change
- Add labels to the mini floating actions buttons that appear, specifically the manual add device button and scan device button.
- Change main floating action button's color to black after clicked.

<img width="99" alt="Screen Shot 2021-02-01 at 9 47 05 AM" src="https://user-images.githubusercontent.com/15002610/106474835-4c5b4a80-6473-11eb-81aa-d6dbb7c2462d.png">

**Comment by sarahelshabrawy** [comment]
Can I work on this issue ?

**Comment by molly34762** [comment]
Task completed
